# Generated by Django 5.1.4 on 2025-01-04 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_encomenda', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada')], max_length=50)),
                ('confirmacao', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glm.fornecedor')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glm.medicamento')),
            ],
        ),
    ]
