# Generated by Django 5.1.4 on 2025-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glm', '0002_encomenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='confirmacao',
            new_name='concluida',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='estado',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
