# Generated by Django 5.1.4 on 2025-01-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glm', '0005_remove_medicamento_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fornecedores',
            field=models.ManyToManyField(blank=True, to='glm.fornecedor'),
        ),
    ]
