# Generated by Django 5.1.4 on 2025-01-01 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('profissao', models.CharField(choices=[('Médico', 'Médico'), ('Enfermeiro', 'Enfermeiro'), ('Farmacêutico', 'Farmacêutico')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('morada', models.TextField()),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condicoes_cronicas', models.TextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpc.profissional')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpc.utente')),
            ],
        ),
    ]
